### ISSUE TITLE
some ruby gem rpms available in base or epel too (but mostly in different versions)

### ISSUE THREAD

**Issue by hoonetorg** [OpenNebula/addon-installgems#12]
A lot rubygems are already available in centos 7 or epel 7 repos.

I sorted the created rpms in
in_base (in centos 7.2 repo - base or updates)
in_epel (in epel 7)
not_in_other_repo (not in centos 7 repos, epel 7, elrepo 7, nux 7)

Especially I'd rather like not to overwrite packages which come with centos / rhel directly:
Is it OK to take 
rubygem-json 
and 
rubygem-thor 
from centos/rhel repos 
(thor is obviously the same version and json not much different)?

What about the versions of rubygems from epel?

Version comparison:

```
in_base:
selfbuild: rubygem-json-1.8.3-1.x86_64.rpm           base: 1.7.7-25.el7_1
selfbuild: rubygem-thor-0.19.1-1.noarch.rpm          base: 0.19.1-1.el7

in_epel:
selfbuild: rubygem-addressable-2.4.0-1.noarch.rpm    epel: 2.3.6-6.el7
selfbuild: rubygem-builder-3.2.2-1.noarch.rpm        epel: 3.1.4-3.el7
selfbuild: rubygem-curb-0.9.1-1.x86_64.rpm           epel: 0.8.5-1.el7
selfbuild: rubygem-eventmachine-1.0.9.1-1.x86_64.rpm epel: 1.0.6-2.el7
selfbuild: rubygem-macaddr-1.7.1-1.noarch.rpm        epel: 1.7.1-2.el7
selfbuild: rubygem-mime-types-2.99.0-1.noarch.rpm    epel: 1.19-3.el7
selfbuild: rubygem-multipart-post-2.0.0-1.noarch.rpm epel: 2.0.0-1.el7
selfbuild: rubygem-net-ldap-0.13.0-1.noarch.rpm      epel: 0.6.1-2.el7
selfbuild: rubygem-nokogiri-1.6.7.1-1.x86_64.rpm     epel: 1.6.1-1.el7.1
selfbuild: rubygem-ox-2.2.3-1.x86_64.rpm             epel: 2.1.8-2.el7
selfbuild: rubygem-rack-1.6.4-1.noarch.rpm           epel: 1:1.5.2-4.el7
selfbuild: rubygem-sqlite3-1.3.11-1.x86_64.rpm       epel: 1.3.5-4.el7
selfbuild: rubygem-systemu-2.6.5-1.noarch.rpm        epel: 2.6.4-1.el7
selfbuild: rubygem-trollop-2.1.2-1.noarch.rpm        epel: 2.0-3.el7
selfbuild: rubygem-uuid-2.3.8-1.noarch.rpm           epel: 2.3.7-1.el7

not_in_other_repo:
rubygem-amazon-ec2-0.9.17-1.noarch.rpm
rubygem-aws-sdk-1.33.0-1.noarch.rpm
rubygem-azure-0.7.1-1.noarch.rpm
rubygem-configparser-0.1.4-1.noarch.rpm
rubygem-daemons-1.2.3-1.noarch.rpm
rubygem-faraday-0.9.2-1.noarch.rpm
rubygem-faraday_middleware-0.10.0-1.noarch.rpm
rubygem-hashie-3.4.3-1.noarch.rpm
rubygem-inflection-1.0.0-1.noarch.rpm
rubygem-memcache-client-1.8.5-1.noarch.rpm
rubygem-mini_portile2-2.0.0-1.noarch.rpm
rubygem-mysql-2.9.1-1.x86_64.rpm
rubygem-parse-cron-0.1.4-1.noarch.rpm
rubygem-polyglot-0.3.5-1.noarch.rpm
rubygem-rack-protection-1.5.3-1.noarch.rpm
rubygem-scrub_rb-1.0.1-1.noarch.rpm
rubygem-sequel-4.30.0-1.noarch.rpm
rubygem-sinatra-1.4.6-1.noarch.rpm
rubygem-softlayer_api-3.2.0-1.noarch.rpm
rubygem-thin-1.6.4-1.x86_64.rpm
rubygem-tilt-2.0.2-1.noarch.rpm
rubygem-treetop-1.6.3-1.noarch.rpm
rubygem-uuidtools-2.1.5-1.noarch.rpm
rubygem-xml-simple-1.1.5-1.noarch.rpm
rubygem-zendesk_api-1.13.3-1.noarch.rpm
```

**Comment by alvarosimon** [comment]
Hi @hoonetorg 

Thanks a lot for your feedback! 
yes now we can find most of the rubygems required  by OpenNebula in epel and centos repos, probably the installgems addon will be not required in the future and that's great!. I have to test this in our testbed with centos7.2 and also if the versions provided by epel and centos are compatible with the ONE versions. About your PR let me some time to test it before merging.

**Comment by hoonetorg** [comment]
Thx for your feedback. Take your time for the PR. Still a lot rubygems are missing. Probably not every missing rubygem is strictly needed for everybody(f.e. rubygem-azure), but some are important for a lot of the customers (f.e. rubygem-mysql )

**Comment by alvarosimon** [comment]
I will close this bug because this should be handled by `opennebula-ruby` package dependencies and also by `install_gems` script which are used by addon-installgems to detect and install the missing gems. 
Probably this feature must be requested in the ONE development portal: http://dev.opennebula.org/
