### ISSUE TITLE
/home/lsimngar/install_gems?

### ISSUE THREAD

**Issue by Madko** [OpenNebula/addon-installgems#2]
Hi,

just a little point missing in the documentation, you need to change the install_gem path line 21.

Best regards,

Edouard

**Comment by Madko** [comment]
On RedHat/CentOS, there is also with createrepo package some more packages needed:

- redhat-lsb
- rpm-build (add to run in debug mode to find this obvious one...)

After that everything works fine. Thanks!

**Comment by alvarosimon** [comment]
Hi @Madko  thanks a lot for your remarks! I will update the doc as soon as possible.

**Comment by alvarosimon** [comment]
Doc updated!. Thanks again for the remarks
