### ISSUE TITLE
gem_packages.py fails on centos 7.1 if gem mini_portile is not installed via "sudo gem install mini_portile"

### ISSUE THREAD

**Issue by hoonetorg** [OpenNebula/addon-installgems#8]
[oneadmin@ncopennebula01 addon-installgems]$ ./gem_packages.py -d
redhat OS flavour detected.
Installing required packages to generate gem packages.
2015-06-01 08:48:56,703 - gem_packages - DEBUG - Running: sudo yum install -y ruby-devel gcc
Intalling fpm gem.
2015-06-01 08:49:00,298 - gem_packages - DEBUG - Running: sudo gem install fpm
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/fpm/package/pyfpm/__init__.pyc, skipping
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/fpm/package/pyfpm/get_metadata.pyc, skipping
Installing required packages to compile new gems.
2015-06-01 08:50:14,652 - gem_packages - DEBUG - Running: /usr/share/one/install_gems --showallpackages
2015-06-01 08:50:14,879 - gem_packages - DEBUG - Running: sudo yum install -y gcc rubygem-rake libxml2-devel libxslt-devel gcc-c++ sqlite-devel curl-devel mysql-devel ruby-devel make 
Compiling required gems.. Please wait.
2015-06-01 08:50:46,125 - gem_packages - DEBUG - Running: /usr/share/one/install_gems --showallgems
2015-06-01 08:50:46,302 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir nokogiri

ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby
	--help
	--clean
	--use-system-libraries
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mini_portile (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:395:in `<main>'

Gem files will remain installed in /var/lib/one/addon-installgems/gems_dir/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /var/lib/one/addon-installgems/gems_dir/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
2015-06-01 08:51:07,820 - gem_packages - DEBUG - Successfully installed mini_portile-0.6.2
Building native extensions.  This could take a while...

2015-06-01 08:51:07,820 - gem_packages - ERROR - exit status 1
[oneadmin@ncopennebula01 addon-installgems]$ 

# then I install mini_portile gem -> et voila

[oneadmin@ncopennebula01 addon-installgems]$ sudo gem install mini_portile
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Parsing documentation for mini_portile-0.6.2
Installing ri documentation for mini_portile-0.6.2
1 gem installed
[oneadmin@ncopennebula01 addon-installgems]$ ./gem_packages.py -d
redhat OS flavour detected.
Installing required packages to generate gem packages.
2015-06-01 09:00:21,981 - gem_packages - DEBUG - Running: sudo yum install -y ruby-devel gcc
Intalling fpm gem.
2015-06-01 09:00:25,113 - gem_packages - DEBUG - Running: sudo gem install fpm
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/fpm/package/pyfpm/__init__.pyc, skipping
unable to convert "\xF3" from ASCII-8BIT to UTF-8 for lib/fpm/package/pyfpm/get_metadata.pyc, skipping
Installing required packages to compile new gems.
2015-06-01 09:00:33,537 - gem_packages - DEBUG - Running: /usr/share/one/install_gems --showallpackages
2015-06-01 09:00:33,848 - gem_packages - DEBUG - Running: sudo yum install -y gcc rubygem-rake libxml2-devel libxslt-devel gcc-c++ sqlite-devel curl-devel mysql-devel ruby-devel make 
Compiling required gems.. Please wait.
2015-06-01 09:00:39,997 - gem_packages - DEBUG - Running: /usr/share/one/install_gems --showallgems
2015-06-01 09:00:40,209 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir nokogiri

2015-06-01 09:02:00,258 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir json

2015-06-01 09:02:06,059 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir thin

2015-06-01 09:02:44,271 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir zendesk_api

2015-06-01 09:03:02,523 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir sqlite3

2015-06-01 09:03:11,424 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir sequel

2015-06-01 09:03:15,472 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir amazon-ec2

2015-06-01 09:03:23,117 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir uuidtools

2015-06-01 09:03:26,065 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir curb

2015-06-01 09:04:00,973 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir net-ldap

2015-06-01 09:04:04,116 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir builder

2015-06-01 09:04:07,228 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir trollop

2015-06-01 09:04:10,122 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir treetop

2015-06-01 09:04:16,892 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir parse-cron

2015-06-01 09:04:19,759 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir aws-sdk --version "= 1.33"

2015-06-01 09:06:00,457 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir ox

2015-06-01 09:06:08,417 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir mysql

2015-06-01 09:06:14,515 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir softlayer_api

2015-06-01 09:06:20,246 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir configparser

2015-06-01 09:06:22,453 - gem_packages - DEBUG - Running: gem install --no-ri --no-rdoc --install-dir /var/lib/one/addon-installgems/gems_dir azure

Creating gem packages.
2015-06-01 09:08:00,231 - gem_packages - DEBUG - Found  RH/CentOS 7.1.1503. prefix set to: /usr/share/gems
2015-06-01 09:08:00,231 - gem_packages - DEBUG - Running: find /var/lib/one/addon-installgems/gems_dir/cache -name '*.gem' | xargs -rn1 fpm --prefix /usr/share/gems -p /var/lib/one/addon-installgems/gems_dir -s gem -x doc -t rpm
2015-06-01 09:11:24,799 - gem_packages - DEBUG - {:timestamp=>"2015-06-01T09:08:01.600848+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:01.656253+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:01.964662+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-rack-1.6.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:03.006624+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:03.018661+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:03.149229+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-mini_portile-0.6.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:04.195070+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:04.215972+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:04.350542+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-multi_json-1.11.0-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:05.479752+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:05.526952+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:05.861615+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-multipart-post-2.0.0-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:06.986509+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:07.018209+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:07.241611+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-amazon-ec2-0.9.17-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:08.695108+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:08.825185+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:09.668540+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-aws-sdk-1.33.0-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:11.347860+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:11.358298+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:11.482025+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-polyglot-0.3.5-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:12.531738+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:12.543370+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:12.676628+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-macaddr-1.7.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:13.685770+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:13.697257+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:13.836495+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-systemu-2.6.5-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:20.742653+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:20.776586+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:22.049440+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-ox-2.2.0-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:08:23.132028+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:23.157001+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:23.315768+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-mime-types-1.25.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:24.346553+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:24.361357+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:24.501042+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-parse-cron-0.1.4-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:25.837059+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:25.859233+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:26.008110+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-trollop-2.1.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:27.167224+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:27.196329+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:27.444901+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-mime-types-2.6.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:28.464419+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:28.477232+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:28.614339+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-uuid-2.3.7-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:42.559086+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:42.619942+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:45.533244+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-eventmachine-1.0.7-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:08:49.538056+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:49.568203+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:50.303486+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-sqlite3-1.3.10-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:08:51.359367+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:51.370009+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:51.503983+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-inflection-1.0.0-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:52.537436+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:52.547287+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:52.677246+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-xml-simple-1.1.5-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:08:54.701528+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:54.730992+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:55.532699+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-thin-1.6.3-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:08:59.672937+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:08:59.698266+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:00.586535+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-mysql-2.9.1-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:09:01.649886+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:01.672977+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:01.816783+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-builder-3.2.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:02.979125+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:03.030685+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:03.220121+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-zendesk_api-1.7.4-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:04.306294+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:04.321485+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:04.453955+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-configparser-0.1.3-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:37.978509+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:38.011629+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:39.227839+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-curb-0.8.8-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:09:40.268024+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:40.297558+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:40.708801+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-softlayer_api-3.0.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:41.782790+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:41.806614+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:41.951820+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-daemons-1.2.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:42.991695+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:43.012419+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:43.150365+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-uuidtools-2.1.5-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:44.199104+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:44.229298+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:44.410110+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-faraday-0.9.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:45.869584+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:45.912328+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:46.115911+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-treetop-1.6.2-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:48.900267+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:48.944910+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:49.653342+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-json-1.8.2-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:09:51.204203+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:51.283131+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:51.584963+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-azure-0.6.4-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:09:52.715865+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:52.743855+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:09:52.908205+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-hashie-3.4.1-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:11:15.168753+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:15.263534+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:19.900838+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-nokogiri-1.6.6.2-1.x86_64.rpm"}
{:timestamp=>"2015-06-01T09:11:21.990787+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:22.124681+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:23.262212+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-sequel-4.22.0-1.noarch.rpm"}
{:timestamp=>"2015-06-01T09:11:24.563593+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:24.597265+0200", :message=>"no value for epoch is set, defaulting to nil", :level=>:warn}
{:timestamp=>"2015-06-01T09:11:24.776027+0200", :message=>"Created package", :path=>"/var/lib/one/addon-installgems/gems_dir/rubygem-net-ldap-0.11.0-1.noarch.rpm"}

**Comment by alvarosimon** [comment]
@hoonetorg thanks for your remarks! I have tested this with Centos7 but I have to check this also in CentOS7.1 in our testbed.
About the warning about generate the rpms in a sandbox I agree, I will include this into the doc as well...

**Comment by alvarosimon** [comment]
@hoonetorg now mini_portile is installed by the script, I have also updated the doc notes. Thanks again for your remarks!

**Comment by hoonetorg** [comment]
@alvarosimon thanks for your quick fix
